# Settings file for VPyMaze

# Program Settings
WINDOW_TITLE = "VPyMaze"
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800
RANDOM_SIZE = False
MANUAL_SOLVE = False
ANIMATE_GENERATION = False
ANIMATE_AUTO_SOLVE = True
SHOW_COORDINATES = False
FIXED_X = 15
FIXED_Y = 15
MAX_SIZE = 40
MIN_SIZE = 5

# Test Settings
SHOW_PIVOTS = False